### ISSUE TITLE
change access to battery minsoc possible?

### ISSUE THREAD

**Issue by Flummi-74** [StefaE/PVOptimize#2]
Hello, I hope this is the right place (I am new to github):

Your project is exactly what I am looking for, thanks for it. But I am unable to set the battery external control and won't get the necessary installer password to set it.

I see, you already use a part of the kostal-RESTAPI from kilianknoll. Would it be possible to change the Battery Minsoc with the kostal-RESTAPI.py (i.e. kostal-RESTAPI -SetMinsoc 30) - you don't need the installers-password to set the battery-control to external, the user-password is enough. (My Kostal runs with 1.17 firmware, here you can change the MinSoc as user). As far as I understand it, the external control works with ModBus and not with the RESTAPI.
Greetings 

Flummi

EDIT: clarified the question.

**Comment by binderth** [comment]
AFAIR, changing the `minSoC` value should be possible via REST-API.

but: you can't be denied the access to your own inverter. Either you should be given the installer password (as this is bound to the personal account of your electrician I doubt they will be keen on giving you that), or they are obliged to change the settings for you (e.g. via remote desktop). 
_Of course it is your own responsibility to use the now available functionality! you could damage the battery or you could force feed-in via battery, which in some cases is not allowed with your network operator._

**Comment by StefaE** [comment]
Hi Flummi,

you are at the right place here :-). The controller you are looking at here, does two things:
1. control EV charging with PV excess power. For that you don't need any control of the home battery
2. **control when and how home battery is charged**

For the latter, it uses multiple API commands:
- `Battery:MinSoc`
- `Battery:SmartBatteryControl:Enable`
- `Battery:ExternControl:MaxChargePowerAbs`
- `Battery:ExternControl:MaxDischargePowerAbs`
- `Battery:ExternControl:MaxSocRel`

Unfortunately, the `ExternControl` commands are only available once enabled with an installer password. In my case, I simply asked my installer to do so ... and he did without a blink. You might check on the [photovoltaikforum](https://www.photovoltaikforum.com/thread/139927-solateur-mit-kostal-service-code-gesucht/?postID=3180605#post3180605) - there are others with same problem for different reasons - propose to also read post #342.

From my side, I could be thinking of providing a switch to only use the _public_ commands. Which makes you ask what I do:

1. set `minSoc` :-)
2. before the sun is so low (in the evening) that production can no longer exceed 70% (old German max feed-in), enable `SmartBatteryControl`
3. ... but that's only half the job: (try to) limit `MaxChargePower` smarter than Kostal smart control does ... - there is some not always successful heuristic here. But at least I give it a try.
4. if EV charging is done with (some) grid power, disable home battery discharge - we could have a long discussion whether that makes sense y/n ...

With only the _public_ commands, I'd basically loose 3/ and 4/. And it would be difficult for me to judge how well 1/ and 2/ alone would do the job ...

**Comment by Flummi-74** [comment]
Thanks for your answers. Now I see, that there is not only the minsoc parameter, which is important. 

The reason why I don't want to mess the battery is, that I am hoping the sell the BYD battery and get a newer, bigger one from my installateur - and he is interested in my battery for someone else, who needs exactly my model as a second battery (he plans a parallel usage). And I don't want them to think, that I am doing "bad" things to the battery. 

So I have to think about it, and may eventually ask my installateur to install an upgrade to version 1.18 and activate the external control button.

**Comment by binderth** [comment]
first of all: all inverters do come with an fail-safe mechanism, which overrides external battery management if need be.
What you _can_ do though is to constantly keep the battery below 10% or at 5% and/or repeatedly charge and discharge the battery at high amps. both things are of course not ideal for LiIon-batteries.
If you only use it like Stefan outlined you're completely safe. And: you need to send constant updates to the inverter (keep-alive), otherwise it will revert to internal battery management.
but: be aware, that your own programming could run into a loop or something, so check it constantly.

oh - you can (and are encouraged to) update the firmware of the inverter, the battery and the KSEM on your own. no need for an installer password for that. Inverter and KSEM can be updated via Web-UI, updating the BYD you need an App (Be Connect 2.0) for it as explained on https://www.bydbatterybox.com/downloads (current _german_ version: https://www.bydbatterybox.com/uploads/downloads/2022-01-11_BYD_Battery-Box_Premium_HVS_HVM_Service_Leitfaden_und_Checkliste_DE_V1.5-620b5ff958006.pdf)

**Comment by Flummi-74** [comment]
Thanks binderth for your answer, I would have one last question: With an update of the Kostal inverter, the KSEM and the BYD - the settings won't get reset? Normally I have no problem to try something and reconfigure it, in case something went wrong - but in this case I won't be able to do it and the damage would be great...

Greetigns

Flummi

**Comment by Flummi-74** [comment]
Nevermind - I tried it as I saw, that there is an Auto-Update Feature since 1.18, so I assume, that it is save to update.

**Comment by Flummi-74** [comment]
... and it worked!!! Thanks, now I think I will call my installateur. Have a nice week.
